DECLARE
    PROCEDURE drop_table_safe(p_table_name VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE ' || p_table_name || ' CASCADE CONSTRAINTS PURGE';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -942 THEN
                RAISE;
            END IF;
    END;
    

    PROCEDURE drop_sequence_safe(p_sequence_name VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || p_sequence_name;
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -2289 THEN
                RAISE;
            END IF;
    END;

BEGIN
    drop_table_safe('PREDICTION_FLAGS');
    drop_table_safe('CHAT_MESSAGES');
    drop_table_safe('EMAIL_LOGS');
    drop_table_safe('REPORTS');
    drop_table_safe('PREDICTIONS');
    drop_table_safe('AI_RECOMMENDATIONS');
    drop_table_safe('STUDENT_FEE_DUES');
    drop_table_safe('COMPLAINTS');
    drop_table_safe('STUDENT_ACADEMIC_RECORDS');
    drop_table_safe('CHAT_SESSIONS');
    drop_table_safe('EMAIL_TEMPLATES');
    drop_table_safe('SUBJECTS');
    drop_table_safe('STUDENTS');
    drop_table_safe('ADMIN_USERS');

    drop_sequence_safe('SEQ_ADMIN_USERS');
    drop_sequence_safe('SEQ_STUDENTS');
    drop_sequence_safe('SEQ_PREDICTIONS');
    drop_sequence_safe('SEQ_EMAIL_LOGS');
    drop_sequence_safe('SEQ_REPORTS');
END;
/

CREATE TABLE admin_users (
    admin_id         VARCHAR2(20) PRIMARY KEY,
    username         VARCHAR2(100) NOT NULL UNIQUE,
    password_hash    VARCHAR2(255) NOT NULL,
    full_name        VARCHAR2(150),
    email            VARCHAR2(150) UNIQUE,
    role_name        VARCHAR2(50) DEFAULT 'Admin' NOT NULL,
    is_active        CHAR(1) DEFAULT 'Y' NOT NULL,
    last_login_at    TIMESTAMP,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_admin_users_active CHECK (is_active IN ('Y','N'))
);

CREATE TABLE students (
    student_id         VARCHAR2(20) PRIMARY KEY,
    full_name          VARCHAR2(150) NOT NULL,
    email              VARCHAR2(150) NOT NULL UNIQUE,
    password_hash      VARCHAR2(255) NOT NULL,
    class_level        VARCHAR2(20) NOT NULL,
    section            VARCHAR2(10) NOT NULL,
    guardian_name      VARCHAR2(150),
    guardian_email     VARCHAR2(150),
    phone_number       VARCHAR2(30),

    performance_index  NUMBER(5,2) DEFAULT 70 NOT NULL,
    risk_level         VARCHAR2(10) DEFAULT 'low' NOT NULL,
    attendance_rate    NUMBER(5,2) DEFAULT 75 NOT NULL,
    due_amount         NUMBER(10,2) DEFAULT 0 NOT NULL,
    complaint_count    NUMBER(5) DEFAULT 0 NOT NULL,
    confidence_score   NUMBER(5,2) DEFAULT 75,

    trend              VARCHAR2(20) DEFAULT 'stable',
    trend_label        VARCHAR2(50),
    trend_note         VARCHAR2(500),

    account_status     VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,

    last_login_at      TIMESTAMP,
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE subjects (
    subject_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_code    VARCHAR2(20) UNIQUE,
    subject_name    VARCHAR2(100) NOT NULL UNIQUE,
    is_active       CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_subjects_active CHECK (is_active IN ('Y','N'))
);

CREATE TABLE student_academic_records (
    record_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id          VARCHAR2(20) NOT NULL,
    subject_id          NUMBER NOT NULL,
    academic_year       NUMBER(4) NOT NULL,
    attendance_rate     NUMBER(5,2) DEFAULT 0 NOT NULL,
    term1_score         NUMBER(5,2) DEFAULT 0 NOT NULL,
    term2_score         NUMBER(5,2) DEFAULT 0 NOT NULL,
    term3_score         NUMBER(5,2) DEFAULT 0 NOT NULL,
    predicted_score     NUMBER(5,2),
    grade               VARCHAR2(5),
    trend               VARCHAR2(20),
    trend_label         VARCHAR2(50),
    ai_recommendation   CLOB,
    last_evaluated_at   TIMESTAMP,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_sar_student FOREIGN KEY (student_id) REFERENCES students(student_id),
    CONSTRAINT fk_sar_subject FOREIGN KEY (subject_id) REFERENCES subjects(subject_id),
    CONSTRAINT uq_sar UNIQUE (student_id, subject_id, academic_year),
    CONSTRAINT ck_sar_att CHECK (attendance_rate BETWEEN 0 AND 100),
    CONSTRAINT ck_sar_t1 CHECK (term1_score BETWEEN 0 AND 100),
    CONSTRAINT ck_sar_t2 CHECK (term2_score BETWEEN 0 AND 100),
    CONSTRAINT ck_sar_t3 CHECK (term3_score BETWEEN 0 AND 100),
    CONSTRAINT ck_sar_pred CHECK (predicted_score IS NULL OR predicted_score BETWEEN 0 AND 100),
    CONSTRAINT ck_sar_trend CHECK (trend IS NULL OR trend IN ('improving','declining','unstable','recovering','stable'))
);

CREATE TABLE complaints (
    complaint_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id           VARCHAR2(20) NOT NULL,
    complaint_type       VARCHAR2(30) NOT NULL,
    description          CLOB,
    severity             VARCHAR2(10) DEFAULT 'MEDIUM' NOT NULL,
    status               VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
    recorded_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    recorded_by_admin_id VARCHAR2(20),
    resolved_at          TIMESTAMP,
    CONSTRAINT fk_complaints_student FOREIGN KEY (student_id) REFERENCES students(student_id),
    CONSTRAINT fk_complaints_admin FOREIGN KEY (recorded_by_admin_id) REFERENCES admin_users(admin_id),
    CONSTRAINT ck_complaint_type CHECK (complaint_type IN ('DISCIPLINARY','ATTENDANCE','ACADEMIC','FINANCE','OTHER')),
    CONSTRAINT ck_complaint_severity CHECK (severity IN ('LOW','MEDIUM','HIGH')),
    CONSTRAINT ck_complaint_status CHECK (status IN ('OPEN','UNDER_REVIEW','RESOLVED','DISMISSED'))
);

CREATE TABLE student_fee_dues (
    fee_due_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id        VARCHAR2(20) NOT NULL,
    term_label        VARCHAR2(50),
    due_title         VARCHAR2(150) NOT NULL,
    amount_due        NUMBER(10,2) NOT NULL,
    amount_paid       NUMBER(10,2) DEFAULT 0 NOT NULL,
    due_date          DATE,
    status            VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    notes             VARCHAR2(500),
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_fee_student FOREIGN KEY (student_id) REFERENCES students(student_id),
    CONSTRAINT ck_fee_due CHECK (amount_due >= 0),
    CONSTRAINT ck_fee_paid CHECK (amount_paid >= 0),
    CONSTRAINT ck_fee_status CHECK (status IN ('PENDING','PARTIAL','PAID','WAIVED','OVERDUE'))
);

CREATE TABLE predictions (
    prediction_id             VARCHAR2(20) PRIMARY KEY,
    student_id                VARCHAR2(20) NOT NULL,
    subject_id                NUMBER NOT NULL,
    subject_name_snapshot     VARCHAR2(100) NOT NULL,
    full_name_snapshot        VARCHAR2(150) NOT NULL,
    class_level_snapshot      VARCHAR2(20) NOT NULL,
    term1_score               NUMBER(5,2) DEFAULT 0 NOT NULL,
    term2_score               NUMBER(5,2) DEFAULT 0 NOT NULL,
    term3_score               NUMBER(5,2) DEFAULT 0 NOT NULL,
    attendance_rate           NUMBER(5,2) DEFAULT 0 NOT NULL,
    complaint_count_snapshot  NUMBER(5) DEFAULT 0 NOT NULL,
    due_amount_snapshot       NUMBER(10,2) DEFAULT 0 NOT NULL,
    predicted_score           NUMBER(5,2) NOT NULL,
    risk_level                VARCHAR2(10) NOT NULL,
    trend                     VARCHAR2(20),
    trend_label               VARCHAR2(50),
    trend_note                VARCHAR2(500),
    grade                     VARCHAR2(5),
    performance_index_label   VARCHAR2(50),
    confidence_score          NUMBER(5,2),
    ai_recommendation         CLOB,
    predicted_by_role         VARCHAR2(20) NOT NULL,
    predicted_by_admin_id     VARCHAR2(20),
    created_at                TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_predictions_student FOREIGN KEY (student_id) REFERENCES students(student_id),
    CONSTRAINT fk_predictions_subject FOREIGN KEY (subject_id) REFERENCES subjects(subject_id),
    CONSTRAINT fk_predictions_admin FOREIGN KEY (predicted_by_admin_id) REFERENCES admin_users(admin_id),
    CONSTRAINT ck_predictions_t1 CHECK (term1_score BETWEEN 0 AND 100),
    CONSTRAINT ck_predictions_t2 CHECK (term2_score BETWEEN 0 AND 100),
    CONSTRAINT ck_predictions_t3 CHECK (term3_score BETWEEN 0 AND 100),
    CONSTRAINT ck_predictions_att CHECK (attendance_rate BETWEEN 0 AND 100),
    CONSTRAINT ck_predictions_due CHECK (due_amount_snapshot >= 0),
    CONSTRAINT ck_predictions_pred CHECK (predicted_score BETWEEN 0 AND 100),
    CONSTRAINT ck_predictions_conf CHECK (confidence_score IS NULL OR confidence_score BETWEEN 0 AND 100),
    CONSTRAINT ck_predictions_risk CHECK (risk_level IN ('low','medium','high')),
    CONSTRAINT ck_predictions_trend CHECK (trend IS NULL OR trend IN ('improving','declining','unstable','recovering','stable')),
    CONSTRAINT ck_predicted_by_role CHECK (predicted_by_role IN ('Admin','Student','System'))
);

CREATE TABLE prediction_flags (
    flag_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prediction_id    VARCHAR2(20) NOT NULL,
    flag_name        VARCHAR2(100) NOT NULL,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_prediction_flags_prediction FOREIGN KEY (prediction_id)
        REFERENCES predictions(prediction_id) ON DELETE CASCADE,
    CONSTRAINT uq_prediction_flag UNIQUE (prediction_id, flag_name)
);

CREATE TABLE ai_recommendations (
    recommendation_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id          VARCHAR2(20) NOT NULL,
    subject_id          NUMBER,
    recommendation_text CLOB NOT NULL,
    rec_type            VARCHAR2(20) DEFAULT 'info' NOT NULL,
    source_type         VARCHAR2(20) DEFAULT 'SYSTEM' NOT NULL,
    is_active           CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_ai_rec_student FOREIGN KEY (student_id) REFERENCES students(student_id),
    CONSTRAINT fk_ai_rec_subject FOREIGN KEY (subject_id) REFERENCES subjects(subject_id),
    CONSTRAINT ck_ai_rec_type CHECK (rec_type IN ('success','warning','danger','info')),
    CONSTRAINT ck_ai_rec_source CHECK (source_type IN ('SYSTEM','ADMIN','MODEL')),
    CONSTRAINT ck_ai_rec_active CHECK (is_active IN ('Y','N'))
);

CREATE TABLE email_templates (
    template_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name      VARCHAR2(100) NOT NULL UNIQUE,
    default_subject    VARCHAR2(300),
    default_body       CLOB,
    is_active          CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_email_templates_active CHECK (is_active IN ('Y','N'))
);

CREATE TABLE email_logs (
    email_id              VARCHAR2(20) PRIMARY KEY,
    student_id            VARCHAR2(20) NOT NULL,
    to_email              VARCHAR2(150) NOT NULL,
    cc_email              VARCHAR2(150),
    template_id           NUMBER,
    subject               VARCHAR2(300) NOT NULL,
    body                  CLOB NOT NULL,
    priority              VARCHAR2(10) DEFAULT 'normal' NOT NULL,
    status                VARCHAR2(10) DEFAULT 'draft' NOT NULL,
    created_by_admin_id   VARCHAR2(20) NOT NULL,
    sent_at               TIMESTAMP,
    created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_email_student FOREIGN KEY (student_id) REFERENCES students(student_id),
    CONSTRAINT fk_email_template FOREIGN KEY (template_id) REFERENCES email_templates(template_id),
    CONSTRAINT fk_email_admin FOREIGN KEY (created_by_admin_id) REFERENCES admin_users(admin_id),
    CONSTRAINT ck_email_priority CHECK (priority IN ('normal','high','urgent')),
    CONSTRAINT ck_email_status CHECK (status IN ('draft','sent','failed'))
);

CREATE TABLE reports (
    report_id              VARCHAR2(20) PRIMARY KEY,
    title                  VARCHAR2(200) NOT NULL,
    report_type            VARCHAR2(50) NOT NULL,
    generated_by_type      VARCHAR2(20) DEFAULT 'ADMIN' NOT NULL,
    generated_by_admin_id  VARCHAR2(20),
    status                 VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    file_path              VARCHAR2(500),
    description            CLOB,
    created_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_reports_admin FOREIGN KEY (generated_by_admin_id) REFERENCES admin_users(admin_id),
    CONSTRAINT ck_reports_generated_by CHECK (generated_by_type IN ('ADMIN','SYSTEM')),
    CONSTRAINT ck_reports_status CHECK (status IN ('DRAFT','PUBLISHED','REVIEW','ESCALATED','ARCHIVED'))
);

CREATE TABLE chat_sessions (
    session_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_role       VARCHAR2(20) NOT NULL,
    admin_id         VARCHAR2(20),
    student_id       VARCHAR2(20),
    session_label    VARCHAR2(200) NOT NULL,
    is_active        CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_sessions_admin FOREIGN KEY (admin_id) REFERENCES admin_users(admin_id),
    CONSTRAINT fk_chat_sessions_student FOREIGN KEY (student_id) REFERENCES students(student_id),
    CONSTRAINT ck_chat_sessions_role CHECK (owner_role IN ('ADMIN','STUDENT')),
    CONSTRAINT ck_chat_sessions_active CHECK (is_active IN ('Y','N')),
    CONSTRAINT ck_chat_sessions_owner CHECK (
        (owner_role = 'ADMIN' AND admin_id IS NOT NULL AND student_id IS NULL)
        OR
        (owner_role = 'STUDENT' AND student_id IS NOT NULL AND admin_id IS NULL)
    )
);

CREATE TABLE chat_messages (
    message_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id       NUMBER NOT NULL,
    sender_type      VARCHAR2(20) NOT NULL,
    message_text     CLOB NOT NULL,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_messages_session FOREIGN KEY (session_id)
        REFERENCES chat_sessions(session_id) ON DELETE CASCADE,
    CONSTRAINT ck_chat_messages_sender CHECK (sender_type IN ('USER','BOT','SYSTEM'))
);

CREATE SEQUENCE seq_admin_users START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_students START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_predictions START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_email_logs START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_reports START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Triggers removed for SYS compatibility.
-- If you run this script in a normal application schema (recommended), you can add ID-generating triggers there.

CREATE INDEX idx_students_class_section ON students(class_level, section);
CREATE INDEX idx_students_risk ON students(risk_level);
-- Removed redundant email index because the UNIQUE constraint on students(email) already creates an index.

CREATE INDEX idx_sar_student_subject ON student_academic_records(student_id, subject_id);
CREATE INDEX idx_complaints_student_date ON complaints(student_id, recorded_at);
CREATE INDEX idx_fee_student_status ON student_fee_dues(student_id, status);

CREATE INDEX idx_predictions_student_date ON predictions(student_id, created_at);
CREATE INDEX idx_predictions_risk ON predictions(risk_level);
CREATE INDEX idx_prediction_flags_prediction ON prediction_flags(prediction_id);

CREATE INDEX idx_ai_rec_student ON ai_recommendations(student_id);
CREATE INDEX idx_email_logs_student_status ON email_logs(student_id, status);
CREATE INDEX idx_reports_status ON reports(status);

CREATE INDEX idx_chat_sessions_student ON chat_sessions(student_id);
CREATE INDEX idx_chat_sessions_admin ON chat_sessions(admin_id);
CREATE INDEX idx_chat_messages_session_time ON chat_messages(session_id, created_at);

INSERT INTO subjects (subject_code, subject_name) VALUES ('MATH', 'Mathematics');
INSERT INTO subjects (subject_code, subject_name) VALUES ('SCI',  'Science');
INSERT INTO subjects (subject_code, subject_name) VALUES ('ENG',  'English');
INSERT INTO subjects (subject_code, subject_name) VALUES ('HIST', 'History');
INSERT INTO subjects (subject_code, subject_name) VALUES ('GEO',  'Geography');
INSERT INTO subjects (subject_code, subject_name) VALUES ('CS',   'Computer Science');
INSERT INTO subjects (subject_code, subject_name) VALUES ('PE',   'Physical Education');

INSERT INTO email_templates (template_name, default_subject, default_body)
VALUES ('Custom Message', NULL, NULL);

INSERT INTO email_templates (template_name, default_subject, default_body)
VALUES ('High Risk Warning',
        'Urgent: High Risk Academic Alert',
        'Dear Student/Guardian,' || CHR(10) ||
        'The student has been flagged as high risk. Please arrange immediate support.');

INSERT INTO email_templates (template_name, default_subject, default_body)
VALUES ('Attendance Alert',
        'Attendance Alert Notice',
        'Dear Student/Guardian,' || CHR(10) ||
        'The attendance rate has dropped below the required threshold.');

INSERT INTO email_templates (template_name, default_subject, default_body)
VALUES ('Fee Dues Reminder',
        'Fee Dues Reminder',
        'Dear Student/Guardian,' || CHR(10) ||
        'This is a reminder that fee dues are still pending.');

INSERT INTO email_templates (template_name, default_subject, default_body)
VALUES ('Performance Improvement Notice',
        'Performance Improvement Notice',
        'Dear Student/Guardian,' || CHR(10) ||
        'The student needs academic support to improve current performance.');

INSERT INTO email_templates (template_name, default_subject, default_body)
VALUES ('Parent Meeting Request',
        'Request for Parent Meeting',
        'Dear Parent/Guardian,' || CHR(10) ||
        'Please attend a meeting with the school administration to discuss student progress.');

-- ADMIN
INSERT INTO admin_users (admin_id, username, password_hash, full_name, email, role_name)
VALUES ('ADM-001', 'admin', 'admin123', 'System Admin', 'admin@school.edu', 'Admin');

-- STUDENTS 

INSERT ALL
    -- Class 10 - Section A
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-001', 'Kaushik Gupta', 'kaushikgupta108@gmail.com', 'student123', 'Class 10', 'A', 'Sanjiv gupta', 'gkaushik22@tbc.edu.np', '9801000001', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-002', 'Aarav Sharma', 'aarav.sharma01@school.edu', 'student123', 'Class 10', 'A', 'Pooja Sharma', 'pooja.sharma01@mail.com', '9801000002', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-003', 'Riya Singh', 'riya.singh01@school.edu', 'student123', 'Class 10', 'A', 'Manoj Singh', 'manoj.singh01@mail.com', '9801000003', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-004', 'Aditya Verma', 'aditya.verma01@school.edu', 'student123', 'Class 10', 'A', 'Sunita Verma', 'sunita.verma01@mail.com', '9801000004', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-005', 'Sneha Joshi', 'sneha.joshi01@school.edu', 'student123', 'Class 10', 'A', 'Ramesh Joshi', 'ramesh.joshi01@mail.com', '9801000005', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-006', 'Rahul Mishra', 'rahul.mishra01@school.edu', 'student123', 'Class 10', 'A', 'Kavita Mishra', 'kavita.mishra01@mail.com', '9801000006', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-007', 'Priya Thapa', 'priya.thapa01@school.edu', 'student123', 'Class 10', 'A', 'Suresh Thapa', 'suresh.thapa01@mail.com', '9801000007', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-008', 'Nabin Karki', 'nabin.karki01@school.edu', 'student123', 'Class 10', 'A', 'Laxmi Karki', 'laxmi.karki01@mail.com', '9801000008', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-009', 'Sanjana Rai', 'sanjana.rai01@school.edu', 'student123', 'Class 10', 'A', 'Dinesh Rai', 'dinesh.rai01@mail.com', '9801000009', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-010', 'Anish Shrestha', 'anish.shrestha01@school.edu', 'student123', 'Class 10', 'A', 'Bimala Shrestha', 'bimala.shrestha01@mail.com', '9801000010', 'ACTIVE')

    -- Class 10 - Section B
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-011', 'Aayush Pandey', 'aayush.pandey01@school.edu', 'student123', 'Class 10', 'B', 'Deepak Pandey', 'deepak.pandey01@mail.com', '9801000011', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-012', 'Neha Yadav', 'neha.yadav01@school.edu', 'student123', 'Class 10', 'B', 'Sita Yadav', 'sita.yadav01@mail.com', '9801000012', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-013', 'Rohan Koirala', 'rohan.koirala01@school.edu', 'student123', 'Class 10', 'B', 'Mina Koirala', 'mina.koirala01@mail.com', '9801000013', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-014', 'Pallavi Chaudhary', 'pallavi.chaudhary01@school.edu', 'student123', 'Class 10', 'B', 'Ashok Chaudhary', 'ashok.chaudhary01@mail.com', '9801000014', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-015', 'Suman Adhikari', 'suman.adhikari01@school.edu', 'student123', 'Class 10', 'B', 'Nirmala Adhikari', 'nirmala.adhikari01@mail.com', '9801000015', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-016', 'Alina Gurung', 'alina.gurung01@school.edu', 'student123', 'Class 10', 'B', 'Bikash Gurung', 'bikash.gurung01@mail.com', '9801000016', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-017', 'Bibek Basnet', 'bibek.basnet01@school.edu', 'student123', 'Class 10', 'B', 'Ganga Basnet', 'ganga.basnet01@mail.com', '9801000017', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-018', 'Muskan Shah', 'muskan.shah01@school.edu', 'student123', 'Class 10', 'B', 'Rajan Shah', 'rajan.shah01@mail.com', '9801000018', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-019', 'Karan KC', 'karan.kc01@school.edu', 'student123', 'Class 10', 'B', 'Anita KC', 'anita.kc01@mail.com', '9801000019', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-020', 'Isha Khadka', 'isha.khadka01@school.edu', 'student123', 'Class 10', 'B', 'Pradeep Khadka', 'pradeep.khadka01@mail.com', '9801000020', 'ACTIVE')

    -- Class 11 - Section A
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-021', 'Saurav Bhandari', 'saurav.bhandari01@school.edu', 'student123', 'Class 11', 'A', 'Kamal Bhandari', 'kamal.bhandari01@mail.com', '9801000021', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-022', 'Asmita Poudel', 'asmita.poudel01@school.edu', 'student123', 'Class 11', 'A', 'Binita Poudel', 'binita.poudel01@mail.com', '9801000022', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-023', 'Roshan Acharya', 'roshan.acharya01@school.edu', 'student123', 'Class 11', 'A', 'Madan Acharya', 'madan.acharya01@mail.com', '9801000023', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-024', 'Nikita Tiwari', 'nikita.tiwari01@school.edu', 'student123', 'Class 11', 'A', 'Shyam Tiwari', 'shyam.tiwari01@mail.com', '9801000024', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-025', 'Kushal Regmi', 'kushal.regmi01@school.edu', 'student123', 'Class 11', 'A', 'Sarita Regmi', 'sarita.regmi01@mail.com', '9801000025', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-026', 'Aastha Jha', 'aastha.jha01@school.edu', 'student123', 'Class 11', 'A', 'Prakash Jha', 'prakash.jha01@mail.com', '9801000026', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-027', 'Prabin Lama', 'prabin.lama01@school.edu', 'student123', 'Class 11', 'A', 'Dolma Lama', 'dolma.lama01@mail.com', '9801000027', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-028', 'Swastika Raut', 'swastika.raut01@school.edu', 'student123', 'Class 11', 'A', 'Hari Raut', 'hari.raut01@mail.com', '9801000028', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-029', 'Yubraj Magar', 'yubraj.magar01@school.edu', 'student123', 'Class 11', 'A', 'Maya Magar', 'maya.magar01@mail.com', '9801000029', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-030', 'Priti Bohora', 'priti.bohora01@school.edu', 'student123', 'Class 11', 'A', 'Tej Bohora', 'tej.bohora01@mail.com', '9801000030', 'ACTIVE')

    -- Class 11 - Section B
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-031', 'Ritesh Neupane', 'ritesh.neupane01@school.edu', 'student123', 'Class 11', 'B', 'Usha Neupane', 'usha.neupane01@mail.com', '9801000031', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-032', 'Sakshi Agrawal', 'sakshi.agrawal01@school.edu', 'student123', 'Class 11', 'B', 'Vijay Agrawal', 'vijay.agrawal01@mail.com', '9801000032', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-033', 'Dipesh Dhakal', 'dipesh.dhakal01@school.edu', 'student123', 'Class 11', 'B', 'Krishna Dhakal', 'krishna.dhakal01@mail.com', '9801000033', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-034', 'Manisha Khatri', 'manisha.khatri01@school.edu', 'student123', 'Class 11', 'B', 'Ram Khatri', 'ram.khatri01@mail.com', '9801000034', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-035', 'Aman Maharjan', 'aman.maharjan01@school.edu', 'student123', 'Class 11', 'B', 'Sabita Maharjan', 'sabita.maharjan01@mail.com', '9801000035', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-036', 'Sujata Oli', 'sujata.oli01@school.edu', 'student123', 'Class 11', 'B', 'Ganesh Oli', 'ganesh.oli01@mail.com', '9801000036', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-037', 'Ayushman BK', 'ayushman.bk01@school.edu', 'student123', 'Class 11', 'B', 'Reena BK', 'reena.bk01@mail.com', '9801000037', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-038', 'Kritika Saha', 'kritika.saha01@school.edu', 'student123', 'Class 11', 'B', 'Naresh Saha', 'naresh.saha01@mail.com', '9801000038', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-039', 'Nischal Sapkota', 'nischal.sapkota01@school.edu', 'student123', 'Class 11', 'B', 'Lila Sapkota', 'lila.sapkota01@mail.com', '9801000039', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-040', 'Elina Chaulagain', 'elina.chaulagain01@school.edu', 'student123', 'Class 11', 'B', 'Bishnu Chaulagain', 'bishnu.chaulagain01@mail.com', '9801000040', 'ACTIVE')

    -- Class 12 - Section A
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-041', 'Sushant Tamang', 'sushant.tamang01@school.edu', 'student123', 'Class 12', 'A', 'Dawa Tamang', 'dawa.tamang01@mail.com', '9801000041', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-042', 'Aditi Giri', 'aditi.giri01@school.edu', 'student123', 'Class 12', 'A', 'Suman Giri', 'suman.giri01@mail.com', '9801000042', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-043', 'Abhishek Pathak', 'abhishek.pathak01@school.edu', 'student123', 'Class 12', 'A', 'Ritu Pathak', 'ritu.pathak01@mail.com', '9801000043', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-044', 'Monika Kandel', 'monika.kandel01@school.edu', 'student123', 'Class 12', 'A', 'Hari Kandel', 'hari.kandel01@mail.com', '9801000044', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-045', 'Arjun Rijal', 'arjun.rijal01@school.edu', 'student123', 'Class 12', 'A', 'Pushpa Rijal', 'pushpa.rijal01@mail.com', '9801000045', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-046', 'Samiksha Kafle', 'samiksha.kafle01@school.edu', 'student123', 'Class 12', 'A', 'Tek Kafle', 'tek.kafle01@mail.com', '9801000046', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-047', 'Bipin Bista', 'bipin.bista01@school.edu', 'student123', 'Class 12', 'A', 'Chandra Bista', 'chandra.bista01@mail.com', '9801000047', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-048', 'Roshni Karki', 'roshni.karki01@school.edu', 'student123', 'Class 12', 'A', 'Nawaraj Karki', 'nawaraj.karki01@mail.com', '9801000048', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-049', 'Aman Shahi', 'aman.shahi01@school.edu', 'student123', 'Class 12', 'A', 'Meera Shahi', 'meera.shahi01@mail.com', '9801000049', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-050', 'Khushi Bhatt', 'khushi.bhatt01@school.edu', 'student123', 'Class 12', 'A', 'Dipak Bhatt', 'dipak.bhatt01@mail.com', '9801000050', 'ACTIVE')

    -- Class 12 - Section B
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-051', 'Niraj Gautam', 'niraj.gautam01@school.edu', 'student123', 'Class 12', 'B', 'Sanjay Gautam', 'sanjay.gautam01@mail.com', '9801000051', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-052', 'Anjali Luitel', 'anjali.luitel01@school.edu', 'student123', 'Class 12', 'B', 'Reeta Luitel', 'reeta.luitel01@mail.com', '9801000052', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-053', 'Sujan Thakur', 'sujan.thakur01@school.edu', 'student123', 'Class 12', 'B', 'Manju Thakur', 'manju.thakur01@mail.com', '9801000053', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-054', 'Pooja Mahato', 'pooja.mahato01@school.edu', 'student123', 'Class 12', 'B', 'Dambar Mahato', 'dambar.mahato01@mail.com', '9801000054', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-055', 'Rupesh Dahal', 'rupesh.dahal01@school.edu', 'student123', 'Class 12', 'B', 'Alka Dahal', 'alka.dahal01@mail.com', '9801000055', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-056', 'Mansi Paudel', 'mansi.paudel01@school.edu', 'student123', 'Class 12', 'B', 'Binod Paudel', 'binod.paudel01@mail.com', '9801000056', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-057', 'Sandeep Khatiwada', 'sandeep.khatiwada01@school.edu', 'student123', 'Class 12', 'B', 'Sushila Khatiwada', 'sushila.khatiwada01@mail.com', '9801000057', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-058', 'Saloni Jaiswal', 'saloni.jaiswal01@school.edu', 'student123', 'Class 12', 'B', 'Ajay Jaiswal', 'ajay.jaiswal01@mail.com', '9801000058', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-059', 'Pratik Kharel', 'pratik.kharel01@school.edu', 'student123', 'Class 12', 'B', 'Indra Kharel', 'indra.kharel01@mail.com', '9801000059', 'ACTIVE')
    INTO students (student_id, full_name, email, password_hash, class_level, section, guardian_name, guardian_email, phone_number, account_status)
    VALUES ('STU-060', 'Diya Baral', 'diya.baral01@school.edu', 'student123', 'Class 12', 'B', 'Gopal Baral', 'gopal.baral01@mail.com', '9801000060', 'ACTIVE')
SELECT 1 FROM dual;

INSERT INTO student_academic_records (
    student_id,
    subject_id,
    academic_year,
    attendance_rate,
    term1_score,
    term2_score,
    term3_score,
    predicted_score,
    grade,
    trend,
    trend_label,
    ai_recommendation,
    last_evaluated_at
)
SELECT
    x.student_id,
    x.subject_id,
    2026,
    x.attendance_rate,
    x.term1_score,
    x.term2_score,
    x.term3_score,
    x.predicted_score,
    CASE
        WHEN x.predicted_score >= 80 THEN 'A'
        WHEN x.predicted_score >= 65 THEN 'B'
        WHEN x.predicted_score >= 50 THEN 'C'
        ELSE 'D'
    END AS grade,
    x.trend,
    CASE
        WHEN x.trend = 'improving' THEN 'Improving'
        WHEN x.trend = 'declining' THEN 'Declining'
        ELSE 'Stable'
    END AS trend_label,
    CASE
        WHEN x.predicted_score < 50 THEN 'Arrange remedial support and weekly follow-up.'
        WHEN x.predicted_score < 65 THEN 'Needs moderate support and more revision practice.'
        ELSE 'Maintain progress with regular study schedule.'
    END AS ai_recommendation,
    CURRENT_TIMESTAMP
FROM (
    SELECT
        s.student_id,
        sub.subject_id,
        LEAST(100, GREATEST(40, s.attendance_rate + MOD(sub.subject_id * 2, 7) - 3)) AS attendance_rate,
        45 + MOD(TO_NUMBER(SUBSTR(s.student_id, 5)) + sub.subject_id * 3, 41) AS term1_score,
        48 + MOD(TO_NUMBER(SUBSTR(s.student_id, 5)) * 2 + sub.subject_id * 5, 38) AS term2_score,
        50 + MOD(TO_NUMBER(SUBSTR(s.student_id, 5)) * 3 + sub.subject_id * 7, 36) AS term3_score,
        ROUND((
            (45 + MOD(TO_NUMBER(SUBSTR(s.student_id, 5)) + sub.subject_id * 3, 41)) +
            (48 + MOD(TO_NUMBER(SUBSTR(s.student_id, 5)) * 2 + sub.subject_id * 5, 38)) +
            (50 + MOD(TO_NUMBER(SUBSTR(s.student_id, 5)) * 3 + sub.subject_id * 7, 36))
        ) / 3, 2) AS predicted_score,
        CASE
            WHEN (50 + MOD(TO_NUMBER(SUBSTR(s.student_id, 5)) * 3 + sub.subject_id * 7, 36))
               - (45 + MOD(TO_NUMBER(SUBSTR(s.student_id, 5)) + sub.subject_id * 3, 41)) >= 8
            THEN 'improving'
            WHEN (45 + MOD(TO_NUMBER(SUBSTR(s.student_id, 5)) + sub.subject_id * 3, 41))
               - (50 + MOD(TO_NUMBER(SUBSTR(s.student_id, 5)) * 3 + sub.subject_id * 7, 36)) >= 8
            THEN 'declining'
            ELSE 'stable'
        END AS trend
    FROM students s
    CROSS JOIN subjects sub
) x;

DECLARE
    v_type      VARCHAR2(30);
    v_severity  VARCHAR2(10);
BEGIN
    FOR s IN (
        SELECT student_id, complaint_count
        FROM students
        WHERE complaint_count > 0
    ) LOOP
        FOR i IN 1 .. s.complaint_count LOOP
            v_type := CASE MOD(i + TO_NUMBER(SUBSTR(s.student_id, 5)), 4)
                        WHEN 0 THEN 'DISCIPLINARY'
                        WHEN 1 THEN 'ATTENDANCE'
                        WHEN 2 THEN 'ACADEMIC'
                        ELSE 'OTHER'
                      END;

            v_severity := CASE
                            WHEN s.complaint_count >= 3 THEN 'HIGH'
                            WHEN s.complaint_count = 2 THEN 'MEDIUM'
                            ELSE 'LOW'
                          END;

            INSERT INTO complaints (
                student_id,
                complaint_type,
                description,
                severity,
                status,
                recorded_at,
                recorded_by_admin_id
            ) VALUES (
                s.student_id,
                v_type,
                'Seeded complaint record for testing for ' || s.student_id,
                v_severity,
                'OPEN',
                CURRENT_TIMESTAMP - NUMTODSINTERVAL((i * 3), 'DAY'),
                'ADM-001'
            );
        END LOOP;
    END LOOP;
END;
/

INSERT INTO student_fee_dues (
    student_id,
    term_label,
    due_title,
    amount_due,
    amount_paid,
    due_date,
    status,
    notes
)
SELECT
    s.student_id,
    '2026 Term 1',
    'Tuition Fee',
    s.due_amount,
    CASE
        WHEN s.due_amount = 15000 THEN 3000
        WHEN s.due_amount = 5000 THEN 0
        ELSE 0
    END AS amount_paid,
    DATE '2026-04-15',
    CASE
        WHEN s.due_amount = 15000 THEN 'OVERDUE'
        WHEN s.due_amount = 5000 THEN 'PENDING'
        ELSE 'PENDING'
    END AS status,
    'Seeded finance record'
FROM students s
WHERE s.due_amount > 0;

INSERT INTO ai_recommendations (
    student_id,
    subject_id,
    recommendation_text,
    rec_type,
    source_type,
    is_active
)
SELECT
    s.student_id,
    sub.subject_id,
    CASE
        WHEN s.risk_level = 'high' THEN 'Provide immediate mentoring, parent communication, and extra classes in Mathematics.'
        WHEN s.risk_level = 'medium' THEN 'Increase revision time and monitor weekly assessment performance in Mathematics.'
        ELSE 'Continue regular study plan and maintain strong attendance in Mathematics.'
    END AS recommendation_text,
    CASE
        WHEN s.risk_level = 'high' THEN 'danger'
        WHEN s.risk_level = 'medium' THEN 'warning'
        ELSE 'success'
    END AS rec_type,
    'SYSTEM',
    'Y'
FROM students s
JOIN subjects sub
    ON sub.subject_code = 'MATH';
    
    
INSERT INTO predictions (
    prediction_id,
    student_id,
    subject_id,
    subject_name_snapshot,
    full_name_snapshot,
    class_level_snapshot,
    term1_score,
    term2_score,
    term3_score,
    attendance_rate,
    complaint_count_snapshot,
    due_amount_snapshot,
    predicted_score,
    risk_level,
    trend,
    trend_label,
    trend_note,
    grade,
    performance_index_label,
    confidence_score,
    ai_recommendation,
    predicted_by_role,
    predicted_by_admin_id,
    created_at
)
SELECT
    'PRD-' || LPAD(ROW_NUMBER() OVER (ORDER BY s.student_id, ar.subject_id), 3, '0') AS prediction_id,
    s.student_id,
    ar.subject_id,
    sub.subject_name,
    s.full_name,
    s.class_level,
    ar.term1_score,
    ar.term2_score,
    ar.term3_score,
    ar.attendance_rate,
    s.complaint_count,
    s.due_amount,
    ar.predicted_score,
    s.risk_level,
    ar.trend,
    ar.trend_label,
    CASE
        WHEN ar.trend = 'declining' THEN 'Performance trend is going downward.'
        WHEN ar.trend = 'improving' THEN 'Performance trend is improving.'
        ELSE 'Performance is mostly stable.'
    END AS trend_note,
    ar.grade,
    CASE
        WHEN ar.predicted_score >= 80 THEN 'Excellent'
        WHEN ar.predicted_score >= 65 THEN 'Good'
        WHEN ar.predicted_score >= 50 THEN 'Average'
        ELSE 'Poor'
    END AS performance_index_label,
    s.confidence_score,
    ar.ai_recommendation,
    'System',
    NULL,
    CURRENT_TIMESTAMP - NUMTODSINTERVAL(TO_NUMBER(SUBSTR(s.student_id, 5)), 'MINUTE')
FROM students s
JOIN student_academic_records ar
    ON ar.student_id = s.student_id
JOIN subjects sub
    ON sub.subject_id = ar.subject_id
WHERE sub.subject_code = 'MATH';


INSERT INTO prediction_flags (prediction_id, flag_name)
SELECT prediction_id, 'POOR ACADEMIC PERFORMANCE'
FROM predictions
WHERE predicted_score < 50;

INSERT INTO prediction_flags (prediction_id, flag_name)
SELECT prediction_id, 'DECLINING TREND'
FROM predictions
WHERE trend = 'declining';

INSERT INTO prediction_flags (prediction_id, flag_name)
SELECT prediction_id, 'HIGH BEHAVIOR RISK'
FROM predictions
WHERE complaint_count_snapshot >= 2;

INSERT INTO prediction_flags (prediction_id, flag_name)
SELECT prediction_id, 'HIGH FINANCIAL RISK'
FROM predictions
WHERE due_amount_snapshot >= 10000;

INSERT INTO prediction_flags (prediction_id, flag_name)
SELECT prediction_id, 'CRITICAL ATTENDANCE'
FROM predictions
WHERE attendance_rate < 60;



INSERT INTO email_logs (
    email_id,
    student_id,
    to_email,
    cc_email,
    template_id,
    subject,
    body,
    priority,
    status,
    created_by_admin_id,
    sent_at
)
SELECT
    'EML-' || LPAD(ROW_NUMBER() OVER (ORDER BY x.student_id), 3, '0') AS email_id,
    x.student_id,
    x.to_email,
    x.cc_email,
    x.template_id,
    x.subject,
    x.body,
    x.priority,
    x.status,
    'ADM-001',
    CASE WHEN x.status = 'sent' THEN CURRENT_TIMESTAMP ELSE NULL END
FROM (
    SELECT
        s.student_id,
        s.email AS to_email,
        s.guardian_email AS cc_email,
        (SELECT template_id FROM email_templates WHERE template_name = 'Performance Improvement Notice') AS template_id,
        'Academic Support Needed' AS subject,
        'This is a demo draft email for academic support follow-up.' AS body,
        'high' AS priority,
        'draft' AS status,
        ROW_NUMBER() OVER (ORDER BY s.student_id) AS rn
    FROM students s
    WHERE s.risk_level = 'high'
) x
WHERE x.rn <= 5;

INSERT INTO email_logs (
    email_id,
    student_id,
    to_email,
    cc_email,
    template_id,
    subject,
    body,
    priority,
    status,
    created_by_admin_id,
    sent_at
)
SELECT
    'EML-' || LPAD(ROW_NUMBER() OVER (ORDER BY x.student_id) + 5, 3, '0') AS email_id,
    x.student_id,
    x.to_email,
    x.cc_email,
    x.template_id,
    x.subject,
    x.body,
    x.priority,
    x.status,
    'ADM-001',
    CURRENT_TIMESTAMP
FROM (
    SELECT
        s.student_id,
        s.email AS to_email,
        s.guardian_email AS cc_email,
        (SELECT template_id FROM email_templates WHERE template_name = 'Fee Dues Reminder') AS template_id,
        'Fee Dues Reminder' AS subject,
        'This is a demo sent email about pending fee dues.' AS body,
        'normal' AS priority,
        'sent' AS status,
        ROW_NUMBER() OVER (ORDER BY s.student_id) AS rn
    FROM students s
    WHERE s.due_amount > 0
) x
WHERE x.rn <= 5;

INSERT INTO chat_sessions (
    owner_role,
    admin_id,
    student_id,
    session_label,
    is_active
) VALUES (
    'ADMIN',
    'ADM-001',
    NULL,
    'Admin support session',
    'Y'
);

INSERT INTO chat_sessions (
    owner_role,
    admin_id,
    student_id,
    session_label,
    is_active
) VALUES (
    'STUDENT',
    NULL,
    'STU-001',
    'Student learning support chat',
    'Y'
);

INSERT INTO chat_sessions (
    owner_role,
    admin_id,
    student_id,
    session_label,
    is_active
) VALUES (
    'STUDENT',
    NULL,
    'STU-002',
    'Attendance advice chat',
    'Y'
);


INSERT INTO chat_messages (session_id, sender_type, message_text)
SELECT session_id, 'USER', 'How can I improve my class performance?'
FROM chat_sessions
WHERE session_label = 'Student learning support chat';

INSERT INTO chat_messages (session_id, sender_type, message_text)
SELECT session_id, 'BOT', 'Focus on attendance, weekly revision, and subject-wise practice.'
FROM chat_sessions
WHERE session_label = 'Student learning support chat';

INSERT INTO chat_messages (session_id, sender_type, message_text)
SELECT session_id, 'USER', 'Why is this student marked as high risk?'
FROM chat_sessions
WHERE session_label = 'Admin support session';

INSERT INTO chat_messages (session_id, sender_type, message_text)
SELECT session_id, 'BOT', 'High risk can be caused by low attendance, weak academic score, complaints, or fee issues.'
FROM chat_sessions
WHERE session_label = 'Admin support session';

INSERT INTO chat_messages (session_id, sender_type, message_text)
SELECT session_id, 'USER', 'My attendance is low. What should I do?'
FROM chat_sessions
WHERE session_label = 'Attendance advice chat';

INSERT INTO chat_messages (session_id, sender_type, message_text)
SELECT session_id, 'BOT', 'Attend classes regularly and communicate early if you miss a class.'
FROM chat_sessions
WHERE session_label = 'Attendance advice chat';

COMMIT;

